# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.2
_src_path: git+https://github.com/shopinvader/shopinvader-addons-repo-template
black_version: 19.10b0
generate_requirements_txt: true
odoo_version: '13.0'
prettify_xml: false
python_line_length: 88
rebel_module_groups: []
repo_slug: odoo-misc
